"""Fix relationship problems

Revision ID: f14a8e72d0d2
Revises: 29e5a12c80b4
Create Date: 2025-08-13 00:27:44.268334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f14a8e72d0d2'
down_revision = '29e5a12c80b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('kyc_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('referral_stat',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('referral_stat',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('kyc_status',
               existing_type=sa.String(length=50),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
